Issue#88 adjust tag line
rockstor/rockstor-website pull request #89
Opened 2023-10-09 19:01 UTC by Hooverdan96

Fixes #88.

- adjusted tag line
- fixed typo in FAQ for customizable platform section

2023-10-09 19:02 UTC, Hooverdan96 commented
Feel free to adjust further!

2023-10-10 10:05 UTC, phillxnet requested changes
@Hooverdan96 Thanks for pushing this one onto a PR.
Made a couple of suggestions - see what you think.

2023-10-10 10:05 UTC, phillxnet commented on content/features/_index.md
> +multiple architectures like AMD64/ARM64EFI/Ten64 and more.
```suggestion
multiple architectures: AMD64 & ARM64EFI.
```
Backing away from the Ten64 mention now given we have Traverse Technologies in our Partners section on the landing page: plus Ten64 is a platform, and an example of ARM64EFI. And we line up our future RISC-V compatibility: an inevitability as we update our base OS and dependencies. I know this looses our Ten64 mention and our Pi4 mention but we have Partner and Pic references prominent, respectively, for both.  Plus we have Pi4 (should add Pi5 once proven) & Ten64 specific downloads; and the Ten64 docs in turn have links back to us.

2023-10-10 10:05 UTC, phillxnet commented on content/solutions/customizable-btrfs-nas-storage-platform.md
> +I/We need more than what Rockstor is; an appliance approach is fine for the majority of cases but not for us.
Thanks, nice fix. Though maybe the original should be been Rocksore. Or maybe Rock-sore-point :) .

2023-10-10 10:40 UTC, phillxnet commented on content/_index.md
> +## An Open Source multi-architecture NAS built on OpenSUSE
Just popping in a side-by-side post my suggestion:
![tag-line-pr-side-by-side_post-suggestion](https://github.com/rockstor/rockstor-website/assets/2521585/edb5957b-eff5-4dcd-a697-bfa33fdaede6)

2023-10-10 14:40 UTC, Hooverdan96 commented
All suggestions accepted, seem to be sensible changes to limit the line spillover and the architecture formulation also makes sense to me.

2023-10-10 15:33 UTC, merged

2023-10-10 15:34 UTC, phillxnet commented
PR product PRODUCTION published.